### ISSUE TITLE
#r "nuget: PowerFx.NET.Interactive, 2024.5.10.9" doesn't works

### ISSUE THREAD

**Issue by lucahttp** [rajyraman/Power-Fx-.NET-Interactive#3]
I'm receiving the following error inside Polyglot notebooks, tbh im not experimented on C Sharp or Nuget Packages

```
Error: C:\Users\sainluca\.packagemanagement\nuget\Projects\12936--cc1add2b-8f30-4a8a-a4c9-57556cddac30\Project.fsproj : error NU1102: Unable to find package Microsoft.PowerFx.Core with version (>= 1.3.0-build.20240423-1001)
C:\Users\sainluca\.packagemanagement\nuget\Projects\12936--cc1add2b-8f30-4a8a-a4c9-57556cddac30\Project.fsproj : error NU1102: - Found 9 version(s) in nuget.org [ Nearest version: 1.2.0 ]
C:\Users\sainluca\.packagemanagement\nuget\Projects\12936--cc1add2b-8f30-4a8a-a4c9-57556cddac30\Project.fsproj : error NU1102: - Found 0 version(s) in C:\Program Files\dotnet\sdk\8.0.302\FSharp\library-packs
C:\Users\sainluca\.packagemanagement\nuget\Projects\12936--cc1add2b-8f30-4a8a-a4c9-57556cddac30\Project.fsproj : error NU1102: Unable to find package Microsoft.PowerFx.Dataverse.Eval with version (>= 1.3.0-build.20240418-1001)
C:\Users\sainluca\.packagemanagement\nuget\Projects\12936--cc1add2b-8f30-4a8a-a4c9-57556cddac30\Project.fsproj : error NU1102: - Found 1 version(s) in nuget.org [ Nearest version: 1.2.0-build.20231002-1005 ]
C:\Users\sainluca\.packagemanagement\nuget\Projects\12936--cc1add2b-8f30-4a8a-a4c9-57556cddac30\Project.fsproj : error NU1102: - Found 0 version(s) in C:\Program Files\dotnet\sdk\8.0.302\FSharp\library-packs
C:\Users\sainluca\.packagemanagement\nuget\Projects\12936--cc1add2b-8f30-4a8a-a4c9-57556cddac30\Project.fsproj : error NU1102: Unable to find package Microsoft.PowerFx.Json with version (>= 1.3.0-build.20240423-1001)
C:\Users\sainluca\.packagemanagement\nuget\Projects\12936--cc1add2b-8f30-4a8a-a4c9-57556cddac30\Project.fsproj : error NU1102: - Found 6 version(s) in nuget.org [ Nearest version: 1.2.0 ]
C:\Users\sainluca\.packagemanagement\nuget\Projects\12936--cc1add2b-8f30-4a8a-a4c9-57556cddac30\Project.fsproj : error NU1102: - Found 0 version(s) in C:\Program Files\dotnet\sdk\8.0.302\FSharp\library-packs
C:\Users\sainluca\.packagemanagement\nuget\Projects\12936--cc1add2b-8f30-4a8a-a4c9-57556cddac30\Project.fsproj : error NU1102: Unable to find package Microsoft.PowerFx.Repl with version (>= 1.3.0-build.20240423-1001)
C:\Users\sainluca\.packagemanagement\nuget\Projects\12936--cc1add2b-8f30-4a8a-a4c9-57556cddac30\Project.fsproj : error NU1102: - Found 1 version(s) in nuget.org [ Nearest version: 1.1.0 ]
C:\Users\sainluca\.packagemanagement\nuget\Projects\12936--cc1add2b-8f30-4a8a-a4c9-57556cddac30\Project.fsproj : error NU1102: - Found 0 version(s) in C:\Program Files\dotnet\sdk\8.0.302\FSharp\library-packs
```

seems that is trying to get libraries that have higher versions that the last published, for example the one of dataverse  
requested: version (>= 1.3.0-build.20240423-1001)
latest: Microsoft.PowerFx.Dataverse.Eval 1.2.0-build.20231002-1005 [url](https://www.nuget.org/packages/Microsoft.PowerFx.Dataverse.Eval/#readme-body-tab)

i was thinking to rebuild the lib following this [example](https://github.com/rajyraman/Power-Fx-.NET-Interactive/blob/main/notebooks/PowerFx.ipynb) 

Install Power Fx - Local Build
#i nuget:D:\GitHub\Power-Fx-.NET-Interactive\src\bin\Debug\
#r "nuget:PowerFx.NET.Interactive"

but I have another questions, how to build this D:\GitHub\Power-Fx-.NET-Interactive\src\bin\Debug\
what I need, the csharp sdk and run a donet build or something like that?

**Comment by lucahttp** [comment]
I has been working on a solution that seems that works,
[https://github.com/lucahttp/Power-Fx-.NET-Interactive](https://github.com/lucahttp/Power-Fx-.NET-Interactive)
and the latest tries are here
[https://github.com/lucahttp/PowerFXPolyglot](https://github.com/lucahttp/PowerFXPolyglot)

but for some reason it says after compile that there is not ClearCollect command available for PowerFX

```
System.AggregateException: One or more errors occurred. (Errors: Error 21-22: Caracteres inesperados. La fórmula contiene "Error" donde se esperaba "ParenClose".

Error 21-22: Caracteres inesperados. Se usan caracteres en la fórmula de forma inesperada.

Error 12-13: 'ClearCollect' is an unknown or unsupported function.

Error 13-21: El nombre no es válido. No se reconoce "Products".)

 ---> System.InvalidOperationException: Errors: Error 21-22: Caracteres inesperados. La fórmula contiene "Error" donde se esperaba "ParenClose".

Error 21-22: Caracteres inesperados. Se usan caracteres en la fórmula de forma inesperada.

Error 12-13: 'ClearCollect' is an unknown or unsupported function.

Error 13-21: El nombre no es válido. No se reconoce "Products".

   at Microsoft.PowerFx.CheckResult.ThrowOnErrors()

   at Microsoft.PowerFx.RecalcEngine.EvalAsync(String expressionText, CancellationToken cancellationToken, ParserOptions options, ReadOnlySymbolTable symbolTable, RuntimeConfig runtimeConfig)

   at Microsoft.PowerFx.RecalcEngine.EvalAsync(String expressionText, CancellationToken cancellationToken, RecordValue parameters, ParserOptions options)

   --- End of inner exception stack trace ---

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)

   at Microsoft.PowerFx.RecalcEngine.Eval(String expressionText, RecordValue parameters, ParserOptions options)

   at PowerFxDotnetInteractive.PowerFxExpression.EvaluateSingleExpression(String originalExpression, String expression, ReadOnlySymbolValues symbolValues)

   at PowerFxDotnetInteractive.PowerFxExpression.<>c__DisplayClass9_0.<Evaluate>b__0(String expression)

   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)

   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()

   at PowerFxDotnetInteractive.PowerFxExpression.Evaluate(ReadOnlySymbolValues symbolValues)

   at PowerFxDotnetInteractive.PowerFxKernel.HandleAsync(SubmitCode submitCode, KernelInvocationContext context)

   at Microsoft.DotNet.Interactive.Kernel.<>c__DisplayClass82_0`1.<SetHandler>b__0(KernelCommand _, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 878

   at Microsoft.DotNet.Interactive.Commands.KernelCommand.InvokeAsync(KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Commands\KernelCommand.cs:line 189

   at Microsoft.DotNet.Interactive.Kernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 330

   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 60

   at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 41```

**Comment by lucahttp** [comment]
fixed by adding nuget source of powerfx daily builds

```dotnet
#i "nuget:https://pkgs.dev.azure.com/Power-Fx/7dd30b4a-31be-4ac9-a649-e6addd4d5b0a/_packaging/PowerFx/nuget/v3/index.json"
#r "nuget:PowerFx.NET.Interactive"
```

working repo to reproduce the notebook and the nuget package build: https://github.com/lucahttp/Polyglot-PowerFx

creating pull request #4

read more of powerfx daily builds here:
// https://github.com/microsoft/Power-Fx/blob/main/dailyBuilds.md
// https://github.com/dotnet/aspnetcore/blob/main/docs/DailyBuilds.md
